apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: giropops-senhas
  name: giropops-senhas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giropops-senhas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
        - name: giropops-senhas
          image: k0dy/giropops-senhas-distroless-projeto:1.0 
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
            requests:
              cpu: '0.5'
              memory: 128Mi
          env:
            - name: REDIS_HOST
              value: redis-service
          imagePullPolicy: Always
         
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"