apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-signed-images
spec:
  validationFailureAction: enforce
  background: false  
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-image-signature
      match:
        any:
        - resources:
            kinds:
            - Pod
      verifyImages:
        - imageReferences:
            - "k0dy/giropops-senhas-distroless-projeto:*"
          mutateDigest: true
          attestors:
          - entries:
            - keys: 
                publicKeys: |-
                 -----BEGIN PUBLIC KEY-----
                 MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETBn5bVBQj9VA3nfIru67bZ6+QYVi
                 1nDDI9b2y3pdjg3vJ26nMYaUlsz/Kk3CgMd1zvVklEwCqhgjYIZCDf64cw==
                 -----END PUBLIC KEY-----          
    - name: validate-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        pattern:
          spec:
            containers:
              - image: "*"
        message: "A imagem '{{request.object.spec.containers[*].image}}' não está assinada com Cosign."