apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor-giropops-senhas
  
  labels:
    app: giropops-senhas
spec:
  selector:
    matchLabels:
      app: giropops-senhas
  podMetricsEndpoints:
    - port: "5000"
      path: /metrics
      interval: 15s