apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: giropops
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  storageClassName: giropops