apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  labels:  
    pvc: redis-pvc  
  name: redis-pvc  
  namespace: giropops
spec:  
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: giropops
  selector:
    matchLabels:
      storage: redis-pv
