apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          #volumeMounts:
            #- mountPath: /data
              #name: redis-persistent-storage
          #securityContext:
            #runAsNonRoot: true
            #readOnlyRootFilesystem: true
          
      #volumes:
        #- name: redis-persistent-storage
          #persistentVolumeClaim:
            #claimName: redis-pvc